/**
 * Deterministic fixtures and adapters for the hosted auth tree.
 *
 * Nothing here is a credential, a captured provider response or a real account.
 * The principals are synthetic numeric IDs, the client secret is a published
 * literal, and every token a test needs is either generated by the production
 * code under test or is an obvious literal padded to a legal length.
 *
 * **This file is test data.** `scripts/check-hosted-modules.mjs` fails the build
 * if any module in `hosted/lib/` or `hosted/functions/` resolves an import into
 * `hosted/test/`, so there is no route by which a fixture reaches a deployed
 * path and no "test mode" flag for a handler to be switched into.
 *
 * ## The two adapters, and why AHU-007 can rely on them
 *
 * `MemoryBlobStore` implements the exact two methods `AuthStore` uses from
 * `@netlify/blobs` — `getWithMetadata` and `setJSON` — with the compare-and-set
 * semantics the real store documents: `onlyIfNew` refuses an existing key,
 * `onlyIfMatch` refuses a stale ETag, and both report the refusal as
 * `{modified: false}` rather than as an exception. Everything AHU-003 claims
 * about single use and revocation is a claim about those semantics, so a
 * consumer testing against this fake is testing against the same rules.
 *
 * `githubProvider` is a fake `fetch` for the two fixed GitHub endpoints. It is
 * narrow on purpose: it answers those two URLs and throws on anything else, so a
 * test that accidentally exercises a third endpoint fails loudly rather than
 * silently receiving a stub.
 */

import { readHostedConfig } from "../../lib/config.mjs";
import { GITHUB_TOKEN_URL, GITHUB_USER_URL } from "../../lib/github-oauth.mjs";
import { AuthStore } from "../../lib/auth-store.mjs";

/* ------------------------------------------------------------------ */
/* principals                                                          */
/* ------------------------------------------------------------------ */

/** A synthetic account. Numeric ID is the identity; login is display only. */
export const PRINCIPAL_ALPHA = Object.freeze({
  accountId: "gh_1010",
  provider: "github.com",
  providerUserId: "1010",
  login: "alpha-example",
});

/** A different account that has taken over `alpha-example`'s old login. */
export const PRINCIPAL_BETA = Object.freeze({
  accountId: "gh_2020",
  provider: "github.com",
  providerUserId: "2020",
  login: "alpha-example",
});

/** The same account as ALPHA, seen after a rename. Same ID, different login. */
export const PRINCIPAL_ALPHA_RENAMED = Object.freeze({
  accountId: "gh_1010",
  provider: "github.com",
  providerUserId: "1010",
  login: "alpha-renamed",
});

/* ------------------------------------------------------------------ */
/* configuration                                                       */
/* ------------------------------------------------------------------ */

/** A complete, valid operator environment. The secret is a published literal. */
export const HOSTED_ENV = Object.freeze({
  HOSTED_APP_ORIGIN: "https://app.archon.example.com",
  HOSTED_RENDER_ORIGIN: "https://render.archon.example.net",
  GITHUB_CLIENT_ID: "Iv1.fixture0client",
  GITHUB_CLIENT_SECRET: "fixture-client-secret-value",
  HOSTED_PUBLISH_ENABLED: "true",
});

/** The validated configuration every route test runs against. */
export function hostedConfig(overrides = {}) {
  return readHostedConfig({ ...HOSTED_ENV, ...overrides });
}

/** The one origin the hosted deployment trusts, for building requests. */
export const APP_ORIGIN = HOSTED_ENV.HOSTED_APP_ORIGIN;

/* ------------------------------------------------------------------ */
/* clock                                                               */
/* ------------------------------------------------------------------ */

/** A clock a test moves by hand. Every expiry assertion runs through one. */
export function fixedClock(startMs = Date.parse("2026-09-09T12:00:00.000Z")) {
  let at = startMs;
  return {
    now: () => at,
    advanceSeconds(seconds) {
      at += seconds * 1000;
      return at;
    },
  };
}

/* ------------------------------------------------------------------ */
/* the store adapter                                                   */
/* ------------------------------------------------------------------ */

/**
 * An in-memory stand-in for a `@netlify/blobs` store, with the real conditional
 * write semantics and deliberate fault injection.
 *
 * `faults` is a list of `{match, mode}`. `match` is a substring of the key and
 * `mode` is one of:
 *
 *   "read"      the next matching `getWithMetadata` throws
 *   "write"     the next matching `setJSON` throws *without* applying
 *   "ambiguous" the next matching `setJSON` applies the write and then throws,
 *               which is the outage a naive implementation reports as a failure
 *               even though the record is now dead
 *   "refuse"    the next matching `setJSON` returns `{modified: false}` without
 *               applying, which is what a lost compare-and-set race looks like
 *
 * Each entry fires once and is removed, so a test can say "fail the first write
 * and then behave" without a stateful reset.
 */
export class MemoryBlobStore {
  constructor() {
    this.entries = new Map();
    this.faults = [];
    this.reads = [];
    this.writes = [];
    this.etagCounter = 0;
  }

  /** Arm one fault. Returns the store so a test can chain it into a constructor. */
  fail(match, mode) {
    this.faults.push({ match, mode });
    return this;
  }

  #takeFault(key, kinds) {
    const index = this.faults.findIndex(
      (fault) => key.includes(fault.match) && kinds.includes(fault.mode),
    );
    if (index === -1) return null;
    return this.faults.splice(index, 1)[0].mode;
  }

  async getWithMetadata(key, options = {}) {
    this.reads.push({ key, options });
    if (this.#takeFault(key, ["read"]) !== null) throw new Error("store read failed");
    const entry = this.entries.get(key);
    if (entry === undefined) return null;
    return { data: structuredClone(entry.data), etag: entry.etag, metadata: {} };
  }

  async setJSON(key, data, conditions = {}) {
    this.writes.push({ key, conditions });
    const fault = this.#takeFault(key, ["write", "ambiguous", "refuse"]);
    if (fault === "write") throw new Error("store write failed");
    if (fault === "refuse") return { modified: false };

    const existing = this.entries.get(key);
    if (conditions.onlyIfNew === true && existing !== undefined) return { modified: false };
    if (conditions.onlyIfMatch !== undefined) {
      if (existing === undefined || existing.etag !== conditions.onlyIfMatch) {
        return { modified: false };
      }
    }
    this.etagCounter += 1;
    const etag = `etag-${this.etagCounter}`;
    this.entries.set(key, { data: structuredClone(data), etag });
    if (fault === "ambiguous") throw new Error("store write failed after applying");
    return { modified: true, etag };
  }

  /** Every key currently present, sorted. Used to assert namespace ownership. */
  keys() {
    return [...this.entries.keys()].sort();
  }
}

/** An `AuthStore` over a fresh memory store and a hand-driven clock. */
export function memoryAuthStore(clock = fixedClock(), store = new MemoryBlobStore()) {
  return { store: new AuthStore(store, { now: clock.now }), blobs: store, clock };
}

/* ------------------------------------------------------------------ */
/* the provider adapter                                                */
/* ------------------------------------------------------------------ */

/** A `Response` carrying JSON, for the fake provider. */
function json(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

/**
 * A fake `fetch` for the two fixed GitHub endpoints.
 *
 * `token` and `user` are the bodies to answer with; either may instead be a
 * function receiving the request, so a test can assert what was sent, or the
 * string `"timeout"`, which rejects the way an aborted fetch does.
 *
 * The default token body carries `refresh_token` and `expires_in`, because the
 * modern OAuth app response does and the point of the fixture is that those
 * fields reach production code and are discarded rather than persisted.
 */
export function githubProvider({
  token = {
    access_token: "fixture-provider-access-token",
    token_type: "bearer",
    scope: "",
    refresh_token: "fixture-provider-refresh-token",
    expires_in: 28800,
    refresh_token_expires_in: 15811200,
  },
  user = { id: 1010, login: "alpha-example" },
  tokenStatus = 200,
  userStatus = 200,
} = {}) {
  const calls = [];
  const answer = async (spec, body, status, request) => {
    if (body === "timeout") throw new Error("The operation was aborted due to timeout");
    if (typeof body === "function") return body(request);
    if (body === "malformed") {
      return new Response("<html>not json</html>", {
        status,
        headers: { "content-type": "text/html" },
      });
    }
    return json(body, status);
  };
  const impl = async (url, request) => {
    calls.push({ url: String(url), request });
    if (String(url) === GITHUB_TOKEN_URL) return answer(url, token, tokenStatus, request);
    if (String(url) === GITHUB_USER_URL) return answer(url, user, userStatus, request);
    throw new Error(`the provider fixture does not serve ${url}`);
  };
  impl.calls = calls;
  return impl;
}

/* ------------------------------------------------------------------ */
/* requests                                                            */
/* ------------------------------------------------------------------ */

/**
 * A `Request` as a browser would send it to a hosted route.
 *
 * `cookies` is a record of name to value and is serialised into one `Cookie`
 * header, which is how a browser sends them and therefore what the production
 * parser has to handle.
 */
export function browserRequest(
  path,
  { method = "GET", cookies = {}, origin = APP_ORIGIN, csrf = null, form = null, json: body = null, headers = {} } = {},
) {
  const sent = new Headers(headers);
  const pairs = Object.entries(cookies);
  if (pairs.length > 0) sent.set("cookie", pairs.map(([name, value]) => `${name}=${value}`).join("; "));
  if (origin !== null) sent.set("origin", origin);
  if (csrf !== null) sent.set("x-archon-csrf", csrf);

  let payload;
  if (form !== null) {
    sent.set("content-type", "application/x-www-form-urlencoded");
    payload = new URLSearchParams(form).toString();
  } else if (body !== null) {
    sent.set("content-type", "application/json");
    payload = JSON.stringify(body);
  }
  return new Request(new URL(path, APP_ORIGIN), { method, headers: sent, body: payload });
}

/** Every `Set-Cookie` on a response, as a name-to-full-value map. */
export function setCookies(response) {
  const found = new Map();
  for (const value of response.headers.getSetCookie()) {
    found.set(value.slice(0, value.indexOf("=")), value);
  }
  return found;
}

/** The value a `Set-Cookie` assigns, which is `""` for a cleared cookie. */
export function cookieValue(serialized) {
  return serialized.slice(serialized.indexOf("=") + 1, serialized.indexOf(";"));
}
